In [1]:
%matplotlib inline

# Week 9 (Course 2, Week 5). Assignment 1.

В этом задании вы сможете немного расслабиться после реализации случайного леса и градиентного бустинга по мотивам материалов прошлой недели. Все, что нужно будет делать — запускать методы из sklearn. Вам предлагается выяснить, какое распределение лучше использовать в наивном байесовском классификаторе в зависимости от вида признаков.

Загрузите датасеты **digits** и **breast_cancer** из sklearn.datasets. Выведите несколько строчек из обучающих выборок и посмотрите на признаки. С помощью **sklearn.cross_validation.cross_val_score** c настройками по умолчанию и вызова метода **mean()** у возвращаемого этой функцией numpy.ndarray, сравните качество работы наивных байесовских классификаторов на этих двух датасетах. Для сравнения предлагается использовать **BernoulliNB**, **MultinomialNB** и **GaussianNB**. Насколько полученные результаты согласуются с рекомендациями из лекций?

In [2]:
from sklearn.datasets import load_digits, load_breast_cancer
from sklearn.cross_validation import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
import pandas as pd
import numpy as np

In [3]:
digits = load_digits()
cancer = load_breast_cancer()

In [4]:
pd_cancer = pd.DataFrame(cancer.data, columns=cancer.feature_names)

In [5]:
pd_cancer.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [6]:
digits.data[:5,:]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.,   0.,   0.,  13.,
         15.,  10.,  15.,   5.,   0.,   0.,   3.,  15.,   2.,   0.,  11.,
          8.,   0.,   0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.,   0.,
          5.,   8.,   0.,   0.,   9.,   8.,   0.,   0.,   4.,  11.,   0.,
          1.,  12.,   7.,   0.,   0.,   2.,  14.,   5.,  10.,  12.,   0.,
          0.,   0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  12.,  13.,   5.,   0.,   0.,   0.,   0.,   0.,
         11.,  16.,   9.,   0.,   0.,   0.,   0.,   3.,  15.,  16.,   6.,
          0.,   0.,   0.,   7.,  15.,  16.,  16.,   2.,   0.,   0.,   0.,
          0.,   1.,  16.,  16.,   3.,   0.,   0.,   0.,   0.,   1.,  16.,
         16.,   6.,   0.,   0.,   0.,   0.,   1.,  16.,  16.,   6.,   0.,
          0.,   0.,   0.,   0.,  11.,  16.,  10.,   0.,   0.],
       [  0.,   0.,   0.,   4.,  15.,  12.,   0.,   0.,   0.,   0.,   3.,
         16.,  15.,  14.,   0.,   0.,   0.,   0.,   8.,  13.

In [7]:
b_digits = cross_val_score(BernoulliNB(), digits.data, digits.target)
b_cancer = cross_val_score(BernoulliNB(), cancer.data, cancer.target)

In [8]:
m_digits = cross_val_score(MultinomialNB(), digits.data, digits.target)
m_cancer = cross_val_score(MultinomialNB(), cancer.data, cancer.target)

In [9]:
g_digits = cross_val_score(GaussianNB(), digits.data, digits.target)
g_cancer = cross_val_score(GaussianNB(), cancer.data, cancer.target)

Два датасета, конечно, еще не повод делать далеко идущие выводы, но при желании вы можете продолжить исследование на других выборках (например, из UCI репозитория).

In [10]:
def write_ans(quest_num, answ):
    with open('assignment_1_%d.txt' % (quest_num,), 'wt') as f:
        f.write(answ)

In [11]:
def print_res(*res):
    for d in res:
        print d, 'Mean:', d.mean(), 'Max:', d.max()
    return np.max(np.hstack(res))

## Вопрос 1
Каким получилось максимальное качество классификации на датасете **breast_cancer**?

In [12]:
r = print_res(b_cancer, m_cancer, g_cancer)
r

[ 0.62631579  0.62631579  0.62962963] Mean: 0.627420402859 Max: 0.62962962963
[ 0.87894737  0.89473684  0.91005291] Mean: 0.894579040193 Max: 0.910052910053
[ 0.91578947  0.94736842  0.94708995] Mean: 0.936749280609 Max: 0.947368421053


0.94736842105263153

In [13]:
write_ans(1, str(r))

In [14]:
%cat assignment_1_1.txt

0.947368421053

## Вопрос 2
Каким получилось максимальное качество классификации на датасете digits?

In [15]:
r = print_res(b_digits, m_digits, g_digits)
r

[ 0.83554817  0.80467446  0.83724832] Mean: 0.825823650778 Max: 0.837248322148
[ 0.8820598   0.85976628  0.87080537] Mean: 0.870877148974 Max: 0.882059800664
[ 0.82392027  0.79966611  0.83221477] Mean: 0.818600380355 Max: 0.832214765101


0.88205980066445178

In [16]:
write_ans(2, str(r))

In [17]:
%cat assignment_1_2.txt

0.882059800664

## Вопрос 3

Выберите верные утверждения и запишите их номера через пробел (в порядке возрастания номера):

1) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли

2) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением

3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков

4) На вещественных признаках лучше всего сработало нормальное распределение

In [18]:
write_ans(3, '3 4')

In [19]:
%cat assignment_1_3.txt

3 4